# Site settings
title: Carmel and Mike
email: hel&#108;o&#64;&#99;&#109;&#46;a&#110;d&#46;mk
url: cm.and.mk
description: Carmel and Mike are getting married. If you wanted to know more - this is the place to come - probably. I\'ll level with you - it\'s all just filler text at the moment.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Carmel and Mike

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Build settings
markdown: kramdown
permalink: pretty
